In [2]:
import numpy as np
X = np.arange(12).reshape(3,4)

X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
np.max(X, axis=1)

array([ 3,  7, 11])

In [4]:
X.sum()

66

In [6]:
X.T.max(axis=0)

array([ 3,  7, 11])

In [7]:
[i.min() for i in X]

[0, 4, 8]

In [8]:
arr = 2*np.arange(0,2,0.5)
if arr <= 0.6:
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy") 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [27]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
x.len()

AttributeError: 'numpy.ndarray' object has no attribute 'len'

In [42]:
a= np.identity(3)
np.where[a == 1] = 300

TypeError: 'function' object does not support item assignment

In [48]:
a=np.zeros((3, 3), int)
x=np.fill_diagonal(a, 300)
a

array([[300,   0,   0],
       [  0, 300,   0],
       [  0,   0, 300]])

## Problem Statement:

### Given a 2d array, write a program to return a subarray such that the subarray consists of the elements from:

1. the second to the fourth row of the original array,

2. the elements in these rows should be from the last three columns of the corresponding rows of the original array,

3. the rows should be in reversed order.

In [59]:
arr = np.array([
     [ 0,  1,  2,  3],  
     [ 4,  5,  6,  7],   
     [ 8,  9, 10, 11],   
     [12, 13, 14, 15],   
     [16, 17, 18, 19]])

In [60]:
arr = arr[1:4, len(arr[0]) - 3:]
arr

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [63]:
np.flip(arr, axis=0)

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

# Problem statement

You are a Teaching Assistant of the DSML course. You have access to every student’s marks in every quiz. The marks are stored in a matrix where matrix[i][j] represents the marks of the ith student in the jth quiz.

The course instructor wants you to sort the marks of students according to jth quiz in increasing order so that he can evaluate the performance of students in that particular quiz.

Here, you have to create a python program using which the instructor can sort the data on the basis of a given column(quiz). The program will return the matrix with the marks sorted in jth quiz.

The dimension of the input matrix is m× n, the output is expected to be a 2d numpy matrix of dimension mxn, but in the output the jth column must be arranged in the ascending order.

Note: The input will be 2D list not array. First convert it to array.

Input Format:

Number of test cases
For each test case, number of rows for matrix and the column to be sorted in a new line.
For each row in matrix, space separated integers are taken as input in a new line.
Output Format:

The 2D matrix, or each row in matrix space separated integers
Sample Input:

1
3 2 
5 3 9
2 1 4
7 6 8
Sample Output:

[[2 1 4]
 [5 3 9]
 [7 6 8]]
Explanation:

The 2nd column of the matrix is [3, 1, 6], the column after sorting becomes [1, 3, 6].

Note: While sorting the marks, take care of rearranging the relative order of rows too. As, [2 1 4] is a row at index 1 in the original matrix, but after sorting the 2nd column, we had to rearrange its order as mentioned in the sample output.