In [1]:
import numpy as np

## Output of the following code

In [3]:
arr = np.arange(16).reshape(4,4)  

print(np.split(arr, 4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


## Which will throw error?

In [13]:
arr = np.arange(10)
print(arr)
np.split(arr, 3) # Only this will throw error
np.split(arr, 5)
np.split(arr, [2, 5])
np.split(arr, [2,12])

[0 1 2 3 4 5 6 7 8 9]


[array([0, 1]), array([2, 3, 4, 5, 6, 7, 8, 9]), array([], dtype=int32)]

In [14]:
import numpy as np
x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1])

1.0


In [15]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1])

21


In [17]:
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])

arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [18]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [19]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

### Problem Statement

- You are given NumPy arrays A, B, and C, where:

`A.shape = (m,)`

`B.shape = (n, 1)`

`C.shape = (n, m)`

- Which of the following operations can be performed on A, B, and C?

`Note: np is the alias for NumPy in the options.`

In [20]:
A = np.arange(3)
A

array([0, 1, 2])

In [35]:
B = np.arange(3).reshape(3, 1)
B

array([[0],
       [1],
       [2]])

In [30]:
C = np.arange(0, 9).reshape(3,3)
C

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
np.concatenate((C, B), axis = 0)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [39]:
np.concatenate((C, A), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [43]:
np.concatenate((C.T, A.reshape(3,1)), axis = 1)

array([[0, 3, 6, 0],
       [1, 4, 7, 1],
       [2, 5, 8, 2]])

In [44]:
np.concatenate((A,B), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### Problem Statement
Given an MxN 2D array (M >= 4),

Split the array column wise such that,

- 1st sub array contains the first 2 columns
- 2nd sub array contains the 3rd column
- 3rd sub array contains the rest of the columns

In [50]:
arr = np.arange(36).reshape(6, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [53]:
np.split(arr, np.array([2, 3]), axis = 1)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26],
        [32]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [2]:
a = np.array([[[ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0],
 [ 0, 0, 0]],
[[ 0, 0, 255],
 [255, 255, 255],
 [ 0, 0, 0],
 [255, 0, 0]]])
b = np.array([255, 0, 255])
c = np.all(a == b, axis = 1) 

In [3]:
c

array([[False,  True, False],
       [False, False, False]])

In [4]:
a

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0],
        [255,   0,   0]]])

In [5]:
b

array([255,   0, 255])

In [6]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr1 = np.hstack((arr, arr[:, 0]))
arr1

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [8]:
np.hstack((arr, arr[:, [0]]))

array([[1, 2, 3, 1],
       [4, 5, 6, 4],
       [7, 8, 9, 7]])