In [2]:
import pandas as pd
import numpy as np

In [6]:
arr = np.arange(9).reshape(3, 3, 1)
arr

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [7]:
arr.shape

(3, 3, 1)

In [10]:
np.squeeze(arr, axis = 2).shape

(3, 3)

In [30]:
arr = np.arange(2, 11, 2)
c1 = arr.view()
np.shares_memory(arr, c1)
arr[0] = 12
c1

arr = 

array([12,  4,  6,  8, 10])

In [35]:
arr = np.array([1,2,3,0,-2,4])

arr1 = arr.reshape(2, 3)
print(arr, arr1)
np.shares_memory(arr, arr1)

[ 1  2  3  0 -2  4] [[ 1  2  3]
 [ 0 -2  4]]


True

#### Which of these would be the correct way to create a dataframe?

In [53]:
# df = pd.DataFrame([[1, 2], ["Ram", "Shyam"], ["IT", "Ops"]], columns = ["emp_id", "name", "dept"]) #----> Throws error

# df = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"]) ---> run perfectly

# df = pd.DataFrame([1, "Ram", "IT"], columns = ["emp_id", "name", "dept"]) this will also throw error

df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})
df

emp_id   name dept
0       1    Ram   IT
1       2  Shyam  Ops

In [55]:
df.columns

Index(['emp_id', 'name', 'dept'], dtype='object')

In [56]:
# df["Imported"] = [i for i in range(2)]
df.insert(2, "imported", [i for i in range(2)])
df

emp_id   name  imported dept
0       1    Ram         0   IT
1       2  Shyam         1  Ops

In [65]:
for x in df.columns:
    print(df[x].nunique())
    if df[x].nunique()==1:
        print(x)
        df.drop(x, axis=1, inplace=True)

2
2
2
2
