In [3]:
import numpy as np

In [4]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])
A + 1

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [5]:
list(map(lambda x:x+1, A))

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [6]:
[x+1 for x in A]

[3, 1, 2, 10, 2, 2, 2, 1, 4, 6]

In [7]:
A+"1"

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('int32'), dtype('<U1')) -> None

In [8]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [9]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 < arr2

array([ True,  True,  True])

In [10]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

birds = np.array([birds])
age = np.array([age])

mask = birds == "Cranes"
age[mask]

array([4. , 5.5])

In [11]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1
x

array([  5,  -9,  20,  25,   3,  -5,  16, -10,  -8])

In [12]:
[1, 2, 3, 4] ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [15]:
np.linspace(0, 10, 100000000000)

MemoryError: Unable to allocate 745. GiB for an array with shape (100000000000,) and data type float64