In [1]:
import pandas as pd
import numpy as np

In [2]:
sachin = pd.read_csv("Sachin_ODI.csv")

sachin.head()

runs  NotOut mins  bf  fours  sixes      sr  Inns           Opp    Ground  \
0    13       0   30  15      3      0   86.66     1   New Zealand    Napier   
1    37       0   75  51      3      1   72.54     2  South Africa  Hamilton   
2    47       0   65  40      7      0  117.50     2     Australia   Dunedin   
3    48       0   37  30      9      1  160.00     2    Bangladesh   Sharjah   
4     4       0   13   9      1      0   44.44     2      Pakistan   Sharjah   

         Date        Winner    Won  century  
0  1995-02-16   New Zealand  False    False  
1  1995-02-18  South Africa  False    False  
2  1995-02-22         India   True    False  
3  1995-04-05         India   True    False  
4  1995-04-07      Pakistan  False    False

Use `sachin_odi.csv` to calculate :

- The Probability of losing and not scoring a century,
- The Probability of losing or not scoring a century.

In [39]:
fav_len = sachin.loc[(~sachin["Won"] & ~sachin["century"])].shape[0]

fav_len

160

In [40]:
print(np.round(fav_len / sachin.shape[0], 2))

0.44


In [41]:
fav_len = sachin.loc[(~sachin["Won"] | ~sachin["century"])].shape[0]

fav_len

330

In [42]:
print(fav_len / sachin.shape[0])

0.9166666666666666


Use `sachin_odi.csv` to calculate

- Probability of “at least three fours” and
- Probability of “at most two fours”

In [5]:
fav_len = sachin.loc[sachin["fours"] >= 3].shape[0]

print(fav_len / sachin.shape[0])

0.5777777777777777


In [8]:
fav_len = sachin.loc[sachin["fours"] <= 2].shape[0]

print(fav_len / sachin.shape[0])

0.4222222222222222


In [10]:
hw = pd.read_csv("weight-height.csv")

hw.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [13]:
fav_len = hw.loc[hw["Height"] <= 70].shape

fav_len

(8122, 3)

In [15]:
print(fav_len[0] / hw.shape[0])

0.8122


In [20]:
die = np.loadtxt("rolling_single_die.txt", dtype="U10")

die = die[1: ]

In [21]:
die

array(['3', '1', '2', ..., '4', '2', '6'], dtype='<U10')

In [22]:
die = np.array(die, dtype = 'int')

die

array([3, 1, 2, ..., 4, 2, 6])

In [23]:
die.shape

(100000,)

In [26]:
die.size

100000

In [27]:
value, counts = np.unique(die, return_counts = True)

(array([1, 2, 3, 4, 5, 6]),
 array([16586, 16721, 16530, 16792, 16820, 16551], dtype=int64))

In [28]:
fav_len = die[die == 3].size

fav_len

16530

In [29]:
print(fav_len / die.size)

0.1653


In [31]:
fav_len = die[die <= 5].size

fav_len

83449

In [32]:
print(fav_len / die.size)

0.83449
